version: '3'
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CLIENT_IP=127.0.0.1
      - CLIENT_PORT=3000
      - DOCKER_CLIENT_PORT_FORWARD=3501
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - SERVER_IP=127.0.0.1
      - SERVER_PORT=3001
      - DOCKER_SERVER_PORT_FORWARD=3500
    env_file:
      - ./backend/.env
